repos:
  # general pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  # license checks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        name: add license header (frontend)
        files: (?<!\.config)\.[jt]sx?$
        args: [--license-filepath, LICENSE_HEADER.txt, --comment-style, "//"]
      - id: insert-license
        name: add license header (backend)
        files: (?<!__init__)\.py$
        args: [--license-filepath, LICENSE_HEADER.txt, --comment-style, "#"]

  # python projects
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: format imports with isort
        language_version: python3
        args: ["--profile", "black"]
        files: \.py$
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        name: format with black
        language_version: python3
        files: \.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: lint with flake8
        args: [--config, tox.ini]
        files: \.py$

  # javascript and typescript projects
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: format with prettier
        files: ^frontend\/.*
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.39.0
    hooks:
      - id: eslint
        name: lint with eslint
        files: \.[jt]sx?$
        types: [file]
