name: build-exploits

on:
  pull_request:
    paths:
      - "exploits/containers/**"
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "exploits/containers/**"

env:
  SQLMAP_VERSION: 1.6.8
  SQLMAP_IMAGE: ghcr.io/dynatrace-oss/invadium-sqlmap
  NMAP_VERSION: 7.92
  NMAP_IMAGE: ghcr.io/dynatrace-oss/invadium-nmap

jobs:
  build-exploits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build and push sqlmap
        uses: docker/build-push-action@v3
        with:
          context: exploits/containers/sqlmap
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.SQLMAP_IMAGE }}:v${{ env.SQLMAP_VERSION }}
            ${{ env.SQLMAP_IMAGE }}:latest
          build-args: |
            SQLMAP_VERSION=${{ env.SQLMAP_VERSION }}
          cache-from: type=registry,ref=${{ env.SQLMAP_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.SQLMAP_IMAGE }}:buildcache,mode=max

      - name: Build and push nmap
        uses: docker/build-push-action@v3
        with:
          context: exploits/containers/nmap
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.NMAP_IMAGE }}:v${{ env.NMAP_VERSION }}
            ${{ env.NMAP_IMAGE }}:latest
          build-args: |
            NMAP_VERSION=${{ env.NMAP_VERSION }}
          cache-from: type=registry,ref=${{ env.NMAP_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.NMAP_IMAGE }}:buildcache,mode=max
